import type { Metadata } from "next";
import "./globals.css";

import { GeistMono } from "geist/font/mono";

import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased bg-black", GeistMono.className)}>{children}</body>
    </html>
  );
}
